name: "Train model"

on: [workflow_dispatch]

permissions:
  contents: read

jobs:
  train:
    runs-on: self-hosted
    env: 
      SNOWFINCH_TRAINING_DATA_PATH: "/home/falco_ghrunner/Snowfinch-acoustics/AI_training_recordings"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run training
      run: |
        python -m src.beggingcallsanalyzer.training.train.py
    - name: Create model artifacts
      uses: actions/upload-artifact@v3
      with:
        name: begging-call-classifier
        path: .out/*
